version: "3.8"
services:
  frontend:
    build: ./frontend
    image: big-o-frontend
    container_name: frontend_app
    command: npm run dev -- --host 0.0.0.0 --port 5173
    ports:
      - '5173:5173'
    depends_on:
      backend:
        condition: service_started
    stdin_open: true
#    environment:
#      NODE_ENV: production
#    volumes:
#      - ./frontend:/frontend
#    volumes:
#      - .:/app
#      - ./node_modules:/app/node_modules
  backend:
    build: ./backend
    image: big-o-backend
    container_name: backend_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - '8000:8000'
    env_file:
      - .env
    stdin_open: true
    tty: true