name: Build and Push to ECR

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: ${{ secrets.AWS_DEV_GITHUB_ACTION_ROLE }}
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-skip-session-tagging: true

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

#      - name: Build & Upload image to ECR
#        uses: appleboy/docker-ecr-action@master
#        with:
#          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          registry: ${{ secrets.REGISTRY }}
#          repo: ${{ env.ECR_REPOSITORY }}
#          region: ${{ env.AWS_REGION }}
#          tags: latest,${{ github.run_number }}
#          daemon_off: false
#          dockerfile: ./Dockerfile
#          context: ./

      - name: Build and Push Images with Docker Compose
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#          REPO: big-o
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build and push all services defined in docker-compose.yaml
          docker compose build
          docker tag big-o-frontend $REGISTRY/big-o-frontend:$IMAGE_TAG
          docker tag big-o-backend $REGISTRY/big-o-backend:$IMAGE_TAG
          docker tag big-o-frontend $REGISTRY/big-o-frontend:latest
          docker tag big-o-backend $REGISTRY/big-o-backend:latest
          docker compose push


